dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t travis-ci-build-stages-demo .
        - docker images
        - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
        - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo # optional, if you don't have registry don't push it
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo /bin/sh -c "cd /code && ./gradlew run"
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo /bin/sh -c "cd /code && ./gradlew run"
